# Generated by Django 3.0.7 on 2020-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='anwered_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='asked_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
