# Generated by Django 3.0.7 on 2020-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200617_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Response'),
        ),
    ]
