# Generated by Django 3.0.7 on 2020-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200617_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='anwered_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
