# Generated by Django 3.0.7 on 2020-06-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200617_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='anwered_on',
            new_name='answered_on',
        ),
    ]
