# Generated by Django 3.0.7 on 2020-06-20 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='starred_by',
            field=models.ManyToManyField(related_name='starred_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
