# Generated by Django 3.0.7 on 2020-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_starred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marked_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answered_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
